export const categories = [
  "All Products",
  "Testosterone Boosters",
  "Pre-Workout",
  "Protein Supplements",
  "Fat Burners",
  "Multivitamins",
  "Recovery & Sleep",
  "Muscle Builders",
];

export const products = [
  {
    id: 1,
    name: "TestoMax Pro",
    category: "Testosterone Boosters",
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.2,
    reviews: 324,
    badge: "Best Seller",
    description: "Natural testosterone booster with D-Aspartic acid and Zinc",
    inStock: true,
    image: "/testoterone.png",
  },
  {
    id: 2,
    name: "Alpha Pump Pre-Workout",
    category: "Pre-Workout",
    price: 39.99,
    originalPrice: 49.99,
    rating: 4.6,
    reviews: 187,
    badge: "New",
    description: "High-stimulant pre-workout for intense training sessions",
    inStock: true,
    image: "/male-enhancement.png",
  },
  {
    id: 3,
    name: "Whey Protein Isolate",
    category: "Protein Supplements",
    price: 69.99,
    originalPrice: null,
    rating: 4.9,
    reviews: 542,
    badge: null,
    description: "25g pure whey protein per serving, fast absorption",
    inStock: true,
    image: "/horny-goat.png",
  },
  {
    id: 5,
    name: "Men's Daily Multi",
    category: "Multivitamins",
    price: 29.99,
    originalPrice: null,
    rating: 4.7,
    reviews: 289,
    badge: null,
    description: "Complete multivitamin formula designed for active men",
    inStock: true,
    image: "/multivitamin.png",
  },
  {
    id: 6,
    name: "Prostate",
    category: "Recovery & Sleep",
    price: 34.99,
    originalPrice: 44.99,
    rating: 4.5,
    reviews: 203,
    badge: null,
    description: "Promotes deep sleep and muscle recovery",
    inStock: true,
    image: "/prostate.png",
  },
];
